<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'sku' => '001',
                'name_en' => 'Wireless Bluetooth Headphones',
                'name_ar' => 'سماعات رأس لاسلكية بتقنية البلوتوث',
                'unit' => 'piece',
                'product_image' => 'products/001.jpg',
                'description_en' => 'Wireless Bluetooth headphones with clear sound and a comfortable design for everyday listening.',
                'description_ar' => 'سماعات رأس لاسلكية بتقنية البلوتوث توفر صوتاً واضحاً وتصميماً مريحاً للاستخدام اليومي.',
            ],
            [
                'sku' => '002',
                'name_en' => 'Bluetooth Portable Speaker',
                'name_ar' => 'مكبر صوت محمول بتقنية البلوتوث',
                'unit' => 'piece',
                'product_image' => 'products/002.jpg',
                'description_en' => 'Compact portable Bluetooth speaker providing clear audio for home, travel, and outdoor use.',
                'description_ar' => 'مكبر صوت محمول ومدمج بتقنية البلوتوث يوفر صوتاً واضحاً للاستخدام في المنزل والسفر والأنشطة الخارجية.',
            ],
            [
                'sku' => '003',
                'name_en' => 'Smartphone 128GB',
                'name_ar' => 'هاتف ذكي بسعة 128 جيجابايت',
                'unit' => 'piece',
                'product_image' => 'products/003.jpg',
                'description_en' => 'Modern smartphone with 128GB of storage, suitable for communication, entertainment, photography, and everyday use.',
                'description_ar' => 'هاتف ذكي حديث بسعة تخزين 128 جيجابايت، مناسب للاتصالات والترفيه والتصوير والاستخدام اليومي.',
            ],
            [
                'sku' => '004',
                'name_en' => 'USB-C Fast Charger 30W',
                'name_ar' => 'شاحن سريع USB-C بقدرة 30 واط',
                'unit' => 'piece',
                'product_image' => 'products/004.jpg',
                'description_en' => '30W USB-C fast charger designed for efficient charging of compatible smartphones, tablets, and other devices.',
                'description_ar' => 'شاحن سريع USB-C بقدرة 30 واط مصمم لشحن الهواتف والأجهزة اللوحية والأجهزة المتوافقة بكفاءة.',
            ],
            [
                'sku' => '005',
                'name_en' => 'Braided USB-C Cable 2m',
                'name_ar' => 'كابل USB-C مضفر بطول مترين',
                'unit' => 'piece',
                'product_image' => 'products/005.jpg',
                'description_en' => 'Durable 2-meter braided USB-C cable suitable for charging and data transfer.',
                'description_ar' => 'كابل USB-C متين ومضفر بطول مترين، مناسب للشحن ونقل البيانات.',
            ],
            [
                'sku' => '006',
                'name_en' => 'Wireless Computer Mouse',
                'name_ar' => 'فأرة كمبيوتر لاسلكية',
                'unit' => 'piece',
                'product_image' => 'products/006.jpg',
                'description_en' => 'Ergonomic wireless computer mouse offering smooth and responsive navigation for everyday work.',
                'description_ar' => 'فأرة كمبيوتر لاسلكية بتصميم مريح توفر تحكماً سلساً واستجابة جيدة للاستخدام اليومي.',
            ],
            [
                'sku' => '007',
                'name_en' => 'Mechanical Keyboard',
                'name_ar' => 'لوحة مفاتيح ميكانيكية',
                'unit' => 'piece',
                'product_image' => 'products/007.jpg',
                'description_en' => 'Mechanical keyboard designed for responsive typing and comfortable long-term computer use.',
                'description_ar' => 'لوحة مفاتيح ميكانيكية مصممة للكتابة السريعة والاستجابة الجيدة والاستخدام المريح لفترات طويلة.',
            ],
            [
                'sku' => '008',
                'name_en' => '27-inch LED Monitor',
                'name_ar' => 'شاشة LED مقاس 27 بوصة',
                'unit' => 'piece',
                'product_image' => 'products/008.jpg',
                'description_en' => '27-inch LED monitor providing a spacious display for work, entertainment, and everyday computing.',
                'description_ar' => 'شاشة LED مقاس 27 بوصة توفر مساحة عرض واسعة للعمل والترفيه والاستخدام اليومي.',
            ],
            [
                'sku' => '009',
                'name_en' => '1080p Webcam',
                'name_ar' => 'كاميرا ويب بدقة 1080 بكسل',
                'unit' => 'piece',
                'product_image' => 'products/009.jpg',
                'description_en' => 'Full HD 1080p webcam suitable for video calls, online meetings, streaming, and remote work.',
                'description_ar' => 'كاميرا ويب بدقة Full HD 1080p مناسبة لمكالمات الفيديو والاجتماعات والبث والعمل عن بعد.',
            ],
            [
                'sku' => '010',
                'name_en' => 'Power Bank 10000mAh',
                'name_ar' => 'بطارية محمولة 10000 مللي أمبير',
                'unit' => 'piece',
                'product_image' => 'products/010.jpg',
                'description_en' => '10000mAh portable power bank for convenient charging of smartphones and compatible devices while away from a power outlet.',
                'description_ar' => 'بطارية محمولة بسعة 10000 مللي أمبير لشحن الهواتف الذكية والأجهزة المتوافقة أثناء التنقل.',
            ],

            [
                'sku' => '011',
                'name_en' => 'Wi-Fi 6 Router',
                'name_ar' => 'راوتر Wi-Fi 6',
                'unit' => 'piece',
                'product_image' => 'products/011.jpg',
                'description_en' => 'Wi-Fi 6 router designed to provide fast and reliable wireless connectivity for homes and offices.',
                'description_ar' => 'راوتر Wi-Fi 6 مصمم لتوفير اتصال لاسلكي سريع وموثوق للمنازل والمكاتب.',
            ],
            [
                'sku' => '012',
                'name_en' => 'Smart LED Bulb',
                'name_ar' => 'مصباح LED ذكي',
                'unit' => 'piece',
                'product_image' => 'products/012.jpg',
                'description_en' => 'Smart LED light bulb suitable for convenient and energy-efficient home lighting.',
                'description_ar' => 'مصباح LED ذكي مناسب للإضاءة المنزلية المريحة والموفرة للطاقة.',
            ],
            [
                'sku' => '013',
                'name_en' => 'Digital Alarm Clock',
                'name_ar' => 'منبه رقمي',
                'unit' => 'piece',
                'product_image' => 'products/013.jpg',
                'description_en' => 'Digital alarm clock with an easy-to-read display for bedrooms, offices, and everyday use.',
                'description_ar' => 'منبه رقمي بشاشة واضحة وسهلة القراءة مناسب لغرف النوم والمكاتب والاستخدام اليومي.',
            ],
            [
                'sku' => '014',
                'name_en' => 'Fitness Smartwatch',
                'name_ar' => 'ساعة ذكية للياقة البدنية',
                'unit' => 'piece',
                'product_image' => 'products/014.jpg',
                'description_en' => 'Fitness smartwatch designed to help monitor daily activity and support an active lifestyle.',
                'description_ar' => 'ساعة ذكية للياقة البدنية تساعد على متابعة النشاط اليومي ودعم نمط حياة نشط.',
            ],
            [
                'sku' => '015',
                'name_en' => 'E-reader 6-inch',
                'name_ar' => 'قارئ إلكتروني مقاس 6 بوصات',
                'unit' => 'piece',
                'product_image' => 'products/015.jpg',
                'description_en' => 'Compact 6-inch e-reader designed for comfortable digital reading at home or while traveling.',
                'description_ar' => 'قارئ إلكتروني مدمج مقاس 6 بوصات مصمم للقراءة الرقمية المريحة في المنزل أو أثناء السفر.',
            ],
            [
                'sku' => '016',
                'name_en' => 'Laptop Backpack',
                'name_ar' => 'حقيبة ظهر للابتوب',
                'unit' => 'piece',
                'product_image' => 'products/016.jpg',
                'description_en' => 'Practical laptop backpack with storage space for a computer, accessories, and everyday essentials.',
                'description_ar' => 'حقيبة ظهر عملية للابتوب توفر مساحة للكمبيوتر والإكسسوارات والأغراض اليومية.',
            ],
            [
                'sku' => '017',
                'name_en' => 'Canvas Tote Bag',
                'name_ar' => 'حقيبة قماش كانفاس',
                'unit' => 'piece',
                'product_image' => 'products/017.jpg',
                'description_en' => 'Reusable canvas tote bag suitable for shopping, work, school, and everyday carrying.',
                'description_ar' => 'حقيبة كانفاس قابلة لإعادة الاستخدام مناسبة للتسوق والعمل والدراسة والاستخدام اليومي.',
            ],
            [
                'sku' => '018',
                'name_en' => 'Travel Duffel Bag',
                'name_ar' => 'حقيبة سفر دافل',
                'unit' => 'piece',
                'product_image' => 'products/018.jpg',
                'description_en' => 'Spacious travel duffel bag suitable for short trips, sports, and carrying personal belongings.',
                'description_ar' => 'حقيبة سفر دافل واسعة مناسبة للرحلات القصيرة والرياضة وحمل الأغراض الشخصية.',
            ],
            [
                'sku' => '019',
                'name_en' => 'Hard Shell Suitcase 24-inch',
                'name_ar' => 'حقيبة سفر صلبة مقاس 24 بوصة',
                'unit' => 'piece',
                'product_image' => 'products/019.jpg',
                'description_en' => '24-inch hard shell suitcase designed to protect belongings during travel.',
                'description_ar' => 'حقيبة سفر صلبة مقاس 24 بوصة مصممة لحماية الأمتعة أثناء السفر.',
            ],
            [
                'sku' => '020',
                'name_en' => 'Leather Wallet',
                'name_ar' => 'محفظة جلدية',
                'unit' => 'piece',
                'product_image' => 'products/020.jpg',
                'description_en' => 'Classic leather wallet designed to organize cash, cards, and personal identification.',
                'description_ar' => 'محفظة جلدية كلاسيكية مصممة لتنظيم النقود والبطاقات والوثائق الشخصية.',
            ],

            [
                'sku' => '021',
                'name_en' => 'Classic Sunglasses',
                'name_ar' => 'نظارات شمسية كلاسيكية',
                'unit' => 'piece',
                'product_image' => 'products/021.jpg',
                'description_en' => 'Classic sunglasses combining everyday style with protection from bright sunlight.',
                'description_ar' => 'نظارات شمسية كلاسيكية تجمع بين الأناقة اليومية والحماية من أشعة الشمس الساطعة.',
            ],
            [
                'sku' => '022',
                'name_en' => 'Analog Wrist Watch',
                'name_ar' => 'ساعة يد بعقارب',
                'unit' => 'piece',
                'product_image' => 'products/022.jpg',
                'description_en' => 'Classic analog wrist watch with a simple design suitable for everyday wear.',
                'description_ar' => 'ساعة يد كلاسيكية بعقارب وتصميم بسيط مناسب للارتداء اليومي.',
            ],
            [
                'sku' => '023',
                'name_en' => 'Cotton T-Shirt',
                'name_ar' => 'قميص تي شيرت قطني',
                'unit' => 'piece',
                'product_image' => 'products/023.jpg',
                'description_en' => 'Comfortable cotton T-shirt suitable for casual everyday wear.',
                'description_ar' => 'قميص تي شيرت قطني مريح مناسب للارتداء اليومي غير الرسمي.',
            ],
            [
                'sku' => '024',
                'name_en' => 'Polo Shirt',
                'name_ar' => 'قميص بولو',
                'unit' => 'piece',
                'product_image' => 'products/024.jpg',
                'description_en' => 'Classic polo shirt offering a smart casual style for everyday occasions.',
                'description_ar' => 'قميص بولو كلاسيكي يوفر مظهراً أنيقاً وغير رسمي للمناسبات اليومية.',
            ],
            [
                'sku' => '025',
                'name_en' => 'Denim Jeans',
                'name_ar' => 'بنطال جينز',
                'unit' => 'piece',
                'product_image' => 'products/025.jpg',
                'description_en' => 'Versatile denim jeans designed for comfortable everyday wear.',
                'description_ar' => 'بنطال جينز عملي ومتعدد الاستخدامات مصمم للراحة أثناء الاستخدام اليومي.',
            ],
            [
                'sku' => '026',
                'name_en' => 'Hooded Sweatshirt',
                'name_ar' => 'سويت شيرت بغطاء رأس',
                'unit' => 'piece',
                'product_image' => 'products/026.jpg',
                'description_en' => 'Comfortable hooded sweatshirt suitable for casual wear and cooler weather.',
                'description_ar' => 'سويت شيرت مريح بغطاء رأس مناسب للارتداء غير الرسمي والطقس البارد.',
            ],
            [
                'sku' => '027',
                'name_en' => 'Lightweight Jacket',
                'name_ar' => 'سترة خفيفة',
                'unit' => 'piece',
                'product_image' => 'products/027.jpg',
                'description_en' => 'Lightweight jacket suitable for layering and everyday outdoor use.',
                'description_ar' => 'سترة خفيفة مناسبة للارتداء فوق الملابس والاستخدام اليومي في الهواء الطلق.',
            ],
            [
                'sku' => '028',
                'name_en' => 'Running Shoes',
                'name_ar' => 'أحذية جري',
                'unit' => 'pair',
                'product_image' => 'products/028.jpg',
                'description_en' => 'Comfortable running shoes designed to support everyday training and active movement.',
                'description_ar' => 'أحذية جري مريحة مصممة لدعم التمارين اليومية والحركة النشطة.',
            ],
            [
                'sku' => '029',
                'name_en' => 'Casual Sneakers',
                'name_ar' => 'أحذية رياضية كاجوال',
                'unit' => 'pair',
                'product_image' => 'products/029.jpg',
                'description_en' => 'Casual sneakers suitable for everyday walking and relaxed outfits.',
                'description_ar' => 'أحذية رياضية كاجوال مناسبة للمشي اليومي والإطلالات غير الرسمية.',
            ],
            [
                'sku' => '030',
                'name_en' => 'Sports Socks 3-Pack',
                'name_ar' => 'جوارب رياضية عبوة 3 قطع',
                'unit' => 'pack',
                'product_image' => 'products/030.jpg',
                'description_en' => 'Three-pack of comfortable sports socks suitable for exercise and everyday activities.',
                'description_ar' => 'عبوة تحتوي على ثلاثة أزواج من الجوارب الرياضية المريحة للتمارين والاستخدام اليومي.',
            ],

            [
                'sku' => '031',
                'name_en' => 'Yoga Mat',
                'name_ar' => 'حصيرة يوغا',
                'unit' => 'piece',
                'product_image' => 'products/031.jpg',
                'description_en' => 'Comfortable yoga mat providing a stable surface for yoga, stretching, and floor exercises.',
                'description_ar' => 'حصيرة يوغا مريحة توفر سطحاً ثابتاً لتمارين اليوغا والتمدد والتمارين الأرضية.',
            ],
            [
                'sku' => '032',
                'name_en' => 'Resistance Bands Set',
                'name_ar' => 'مجموعة أحزمة مقاومة',
                'unit' => 'set',
                'product_image' => 'products/032.jpg',
                'description_en' => 'Set of resistance bands suitable for strength training, stretching, and home workouts.',
                'description_ar' => 'مجموعة أحزمة مقاومة مناسبة لتدريبات القوة والتمدد والتمارين المنزلية.',
            ],
            [
                'sku' => '033',
                'name_en' => 'Adjustable Dumbbell',
                'name_ar' => 'دمبل قابل للتعديل',
                'unit' => 'piece',
                'product_image' => 'products/033.jpg',
                'description_en' => 'Adjustable dumbbell designed for versatile strength training at home or in the gym.',
                'description_ar' => 'دمبل قابل للتعديل مصمم لتدريبات القوة المتنوعة في المنزل أو النادي الرياضي.',
            ],
            [
                'sku' => '034',
                'name_en' => 'Stainless Steel Water Bottle',
                'name_ar' => 'زجاجة مياه من الستانلس ستيل',
                'unit' => 'piece',
                'product_image' => 'products/034.jpg',
                'description_en' => 'Reusable stainless steel water bottle suitable for work, sports, travel, and everyday hydration.',
                'description_ar' => 'زجاجة مياه قابلة لإعادة الاستخدام مصنوعة من الستانلس ستيل، مناسبة للعمل والرياضة والسفر.',
            ],
            [
                'sku' => '035',
                'name_en' => 'Camping Lantern',
                'name_ar' => 'فانوس تخييم',
                'unit' => 'piece',
                'product_image' => 'products/035.jpg',
                'description_en' => 'Portable camping lantern providing convenient lighting for outdoor trips and camping.',
                'description_ar' => 'فانوس تخييم محمول يوفر إضاءة مريحة للرحلات والأنشطة الخارجية والتخييم.',
            ],
            [
                'sku' => '036',
                'name_en' => 'Foldable Camping Chair',
                'name_ar' => 'كرسي تخييم قابل للطي',
                'unit' => 'piece',
                'product_image' => 'products/036.jpg',
                'description_en' => 'Foldable camping chair designed for convenient seating during outdoor activities and trips.',
                'description_ar' => 'كرسي تخييم قابل للطي مصمم للجلوس بشكل مريح أثناء الرحلات والأنشطة الخارجية.',
            ],
            [
                'sku' => '037',
                'name_en' => 'Hiking Backpack 30L',
                'name_ar' => 'حقيبة ظهر للمشي 30 لتر',
                'unit' => 'piece',
                'product_image' => 'products/037.jpg',
                'description_en' => '30-liter hiking backpack providing practical storage for outdoor adventures and day trips.',
                'description_ar' => 'حقيبة ظهر للمشي بسعة 30 لتراً توفر مساحة عملية للرحلات والمغامرات الخارجية.',
            ],
            [
                'sku' => '038',
                'name_en' => 'Picnic Blanket',
                'name_ar' => 'بطانية نزهات',
                'unit' => 'piece',
                'product_image' => 'products/038.jpg',
                'description_en' => 'Portable picnic blanket suitable for parks, beaches, outdoor gatherings, and family trips.',
                'description_ar' => 'بطانية نزهات محمولة مناسبة للحدائق والشواطئ والتجمعات الخارجية والرحلات العائلية.',
            ],
            [
                'sku' => '039',
                'name_en' => 'Football',
                'name_ar' => 'كرة قدم',
                'unit' => 'piece',
                'product_image' => 'products/039.jpg',
                'description_en' => 'Football suitable for recreational games, training sessions, and outdoor activities.',
                'description_ar' => 'كرة قدم مناسبة للمباريات الترفيهية والتدريب والأنشطة الرياضية الخارجية.',
            ],
            [
                'sku' => '040',
                'name_en' => 'Basketball',
                'name_ar' => 'كرة سلة',
                'unit' => 'piece',
                'product_image' => 'products/040.jpg',
                'description_en' => 'Basketball designed for recreational play, training, and outdoor or indoor games.',
                'description_ar' => 'كرة سلة مناسبة للعب الترفيهي والتدريب والمباريات الداخلية أو الخارجية.',
            ],
            [
                'sku' => '041',
                'name_en' => 'Tennis Racket',
                'name_ar' => 'مضرب تنس',
                'unit' => 'piece',
                'product_image' => 'products/041.jpg',
                'description_en' => 'Tennis racket suitable for recreational players and regular practice sessions.',
                'description_ar' => 'مضرب تنس مناسب للاعبين الترفيهيين ولجلسات التدريب المنتظمة.',
            ],
            [
                'sku' => '042',
                'name_en' => 'Table Tennis Set',
                'name_ar' => 'مجموعة تنس طاولة',
                'unit' => 'set',
                'product_image' => 'products/042.jpg',
                'description_en' => 'Table tennis set containing essential equipment for casual games and recreational play.',
                'description_ar' => 'مجموعة تنس طاولة تحتوي على المعدات الأساسية للعب الترفيهي والمباريات غير الرسمية.',
            ],
            [
                'sku' => '043',
                'name_en' => 'Jump Rope',
                'name_ar' => 'حبل قفز',
                'unit' => 'piece',
                'product_image' => 'products/043.jpg',
                'description_en' => 'Jump rope suitable for cardio workouts, fitness training, and warm-up exercises.',
                'description_ar' => 'حبل قفز مناسب لتمارين الكارديو واللياقة البدنية وتمارين الإحماء.',
            ],
            [
                'sku' => '044',
                'name_en' => 'Foam Roller',
                'name_ar' => 'أسطوانة فوم للتدليك',
                'unit' => 'piece',
                'product_image' => 'products/044.jpg',
                'description_en' => 'Foam roller designed for stretching, mobility exercises, and post-workout muscle recovery.',
                'description_ar' => 'أسطوانة فوم مناسبة للتمدد وتمارين الحركة والمساعدة على تعافي العضلات بعد التمرين.',
            ],
            [
                'sku' => '045',
                'name_en' => 'Kettlebell 8kg',
                'name_ar' => 'كتل بيل 8 كجم',
                'unit' => 'piece',
                'product_image' => 'products/045.jpg',
                'description_en' => '8kg kettlebell suitable for strength training, functional workouts, and conditioning exercises.',
                'description_ar' => 'كتل بيل بوزن 8 كجم مناسب لتدريبات القوة والتمارين الوظيفية وتمارين اللياقة.',
            ],

            [
                'sku' => '046',
                'name_en' => 'Electric Screwdriver',
                'name_ar' => 'مفك براغي كهربائي',
                'unit' => 'piece',
                'product_image' => 'products/046.jpg',
                'description_en' => 'Electric screwdriver designed for convenient tightening and loosening of screws during home and workshop projects.',
                'description_ar' => 'مفك براغي كهربائي لتسهيل ربط وفك البراغي في المشاريع المنزلية وأعمال الورش.',
            ],
            [
                'sku' => '047',
                'name_en' => 'Cordless Drill',
                'name_ar' => 'مثقاب لاسلكي',
                'unit' => 'piece',
                'product_image' => 'products/047.jpg',
                'description_en' => 'Cordless drill suitable for drilling, fastening, and general DIY and workshop tasks.',
                'description_ar' => 'مثقاب لاسلكي مناسب للحفر والتثبيت ومهام الأعمال اليدوية والورش المختلفة.',
            ],
            [
                'sku' => '048',
                'name_en' => 'Hammer',
                'name_ar' => 'مطرقة',
                'unit' => 'piece',
                'product_image' => 'products/048.jpg',
                'description_en' => 'General-purpose hammer suitable for household repairs, assembly, and workshop tasks.',
                'description_ar' => 'مطرقة متعددة الاستخدامات مناسبة للإصلاحات المنزلية والتركيب وأعمال الورش.',
            ],
            [
                'sku' => '049',
                'name_en' => 'Adjustable Wrench',
                'name_ar' => 'مفتاح ربط قابل للتعديل',
                'unit' => 'piece',
                'product_image' => 'products/049.jpg',
                'description_en' => 'Adjustable wrench suitable for tightening and loosening nuts and bolts of different sizes.',
                'description_ar' => 'مفتاح ربط قابل للتعديل مناسب لربط وفك الصواميل والمسامير بأحجام مختلفة.',
            ],
            [
                'sku' => '050',
                'name_en' => 'Screwdriver Set',
                'name_ar' => 'مجموعة مفكات براغي',
                'unit' => 'set',
                'product_image' => 'products/050.jpg',
                'description_en' => 'Multi-piece screwdriver set suitable for household repairs, electronics, furniture, and general maintenance.',
                'description_ar' => 'مجموعة مفكات متعددة القطع مناسبة للإصلاحات المنزلية والإلكترونيات والأثاث والصيانة العامة.',
            ],
            [
                'sku' => '051',
                'name_en' => 'Tape Measure 5m',
                'name_ar' => 'شريط قياس 5 أمتار',
                'unit' => 'piece',
                'product_image' => 'products/051.jpg',
                'description_en' => '5-meter tape measure for accurate measurements in home improvement, construction, and DIY projects.',
                'description_ar' => 'شريط قياس بطول 5 أمتار للقياسات الدقيقة في أعمال البناء والصيانة والمشاريع المنزلية.',
            ],
            [
                'sku' => '052',
                'name_en' => 'Utility Knife',
                'name_ar' => 'سكين متعدد الاستخدامات',
                'unit' => 'piece',
                'product_image' => 'products/052.jpg',
                'description_en' => 'Utility knife suitable for cutting cardboard, packaging materials, and various household materials.',
                'description_ar' => 'سكين متعدد الاستخدامات مناسب لقطع الكرتون ومواد التغليف والمواد المنزلية المختلفة.',
            ],
            [
                'sku' => '053',
                'name_en' => 'Pliers Set',
                'name_ar' => 'مجموعة كماشات',
                'unit' => 'set',
                'product_image' => 'products/053.jpg',
                'description_en' => 'Set of pliers suitable for gripping, bending, cutting, and general repair tasks.',
                'description_ar' => 'مجموعة كماشات مناسبة للإمساك والثني والقطع ومهام الإصلاح العامة.',
            ],
            [
                'sku' => '054',
                'name_en' => 'Hex Key Set',
                'name_ar' => 'مجموعة مفاتيح سداسية',
                'unit' => 'set',
                'product_image' => 'products/054.jpg',
                'description_en' => 'Hex key set containing different sizes for furniture assembly, machinery, and maintenance tasks.',
                'description_ar' => 'مجموعة مفاتيح سداسية بأحجام مختلفة مناسبة لتركيب الأثاث وصيانة المعدات والآلات.',
            ],
            [
                'sku' => '055',
                'name_en' => 'Tool Box',
                'name_ar' => 'صندوق أدوات',
                'unit' => 'piece',
                'product_image' => 'products/055.jpg',
                'description_en' => 'Practical tool box designed to organize and transport hand tools and accessories.',
                'description_ar' => 'صندوق أدوات عملي مصمم لتنظيم ونقل الأدوات اليدوية والإكسسوارات.',
            ],

            [
                'sku' => '056',
                'name_en' => 'Garden Hose 20m',
                'name_ar' => 'خرطوم حديقة 20 متراً',
                'unit' => 'piece',
                'product_image' => 'products/056.jpg',
                'description_en' => '20-meter garden hose suitable for watering plants, lawns, and outdoor cleaning.',
                'description_ar' => 'خرطوم حديقة بطول 20 متراً مناسب لري النباتات والعشب والتنظيف الخارجي.',
            ],
            [
                'sku' => '057',
                'name_en' => 'Pruning Shears',
                'name_ar' => 'مقص تقليم',
                'unit' => 'piece',
                'product_image' => 'products/057.jpg',
                'description_en' => 'Pruning shears designed for trimming branches, stems, and garden plants.',
                'description_ar' => 'مقص تقليم مصمم لقص الفروع والسيقان والنباتات في الحديقة.',
            ],
            [
                'sku' => '058',
                'name_en' => 'Plant Pot',
                'name_ar' => 'أصيص نباتات',
                'unit' => 'piece',
                'product_image' => 'products/058.jpg',
                'description_en' => 'Plant pot suitable for growing and displaying indoor and outdoor plants.',
                'description_ar' => 'أصيص نباتات مناسب لزراعة وعرض النباتات الداخلية والخارجية.',
            ],
            [
                'sku' => '059',
                'name_en' => 'Watering Can',
                'name_ar' => 'إبريق سقي النباتات',
                'unit' => 'piece',
                'product_image' => 'products/059.jpg',
                'description_en' => 'Watering can designed for convenient and controlled watering of plants and flowers.',
                'description_ar' => 'إبريق سقي مصمم لري النباتات والزهور بطريقة مريحة ومنظمة.',
            ],

            [
                'sku' => '060',
                'name_en' => 'LED Desk Lamp',
                'name_ar' => 'مصباح مكتب LED',
                'unit' => 'piece',
                'product_image' => 'products/060.jpg',
                'description_en' => 'LED desk lamp providing focused lighting for reading, studying, and office work.',
                'description_ar' => 'مصباح مكتب LED يوفر إضاءة مركزة للقراءة والدراسة والعمل المكتبي.',
            ],
            [
                'sku' => '061',
                'name_en' => 'Office Chair',
                'name_ar' => 'كرسي مكتب',
                'unit' => 'piece',
                'product_image' => 'products/061.jpg',
                'description_en' => 'Comfortable office chair designed for extended periods of desk work and computer use.',
                'description_ar' => 'كرسي مكتب مريح مصمم لفترات العمل الطويلة على المكتب واستخدام الكمبيوتر.',
            ],
            [
                'sku' => '062',
                'name_en' => 'Notebook A5',
                'name_ar' => 'دفتر ملاحظات A5',
                'unit' => 'piece',
                'product_image' => 'products/062.jpg',
                'description_en' => 'A5 notebook suitable for notes, planning, journaling, school, and office use.',
                'description_ar' => 'دفتر ملاحظات مقاس A5 مناسب لتدوين الملاحظات والتخطيط والدراسة والعمل المكتبي.',
            ],
            [
                'sku' => '063',
                'name_en' => 'Ballpoint Pens 10-Pack',
                'name_ar' => 'أقلام حبر جاف عبوة 10 قطع',
                'unit' => 'pack',
                'product_image' => 'products/063.jpg',
                'description_en' => 'Pack of 10 reliable ballpoint pens suitable for school, office, and everyday writing.',
                'description_ar' => 'عبوة تحتوي على 10 أقلام حبر جاف مناسبة للدراسة والمكتب والكتابة اليومية.',
            ],
            [
                'sku' => '064',
                'name_en' => 'Mechanical Pencil',
                'name_ar' => 'قلم رصاص ميكانيكي',
                'unit' => 'piece',
                'product_image' => 'products/064.jpg',
                'description_en' => 'Mechanical pencil providing precise and convenient writing for school, office, and technical work.',
                'description_ar' => 'قلم رصاص ميكانيكي يوفر كتابة دقيقة ومريحة للدراسة والمكتب والأعمال الفنية.',
            ],
            [
                'sku' => '065',
                'name_en' => 'Highlighter Set',
                'name_ar' => 'مجموعة أقلام تمييز',
                'unit' => 'set',
                'product_image' => 'products/065.jpg',
                'description_en' => 'Highlighter set for emphasizing important information in notes, documents, and study materials.',
                'description_ar' => 'مجموعة أقلام تمييز لإبراز المعلومات المهمة في الملاحظات والمستندات والمواد الدراسية.',
            ],
            [
                'sku' => '066',
                'name_en' => 'Sticky Notes Pack',
                'name_ar' => 'عبوة ملاحظات لاصقة',
                'unit' => 'pack',
                'product_image' => 'products/066.jpg',
                'description_en' => 'Sticky notes pack suitable for reminders, notes, organization, and office or study tasks.',
                'description_ar' => 'عبوة ملاحظات لاصقة مناسبة للتذكيرات وتدوين الملاحظات والتنظيم والدراسة والعمل.',
            ],
            [
                'sku' => '067',
                'name_en' => 'Desk Organizer',
                'name_ar' => 'منظم مكتب',
                'unit' => 'piece',
                'product_image' => 'products/067.jpg',
                'description_en' => 'Desk organizer designed to keep pens, stationery, and small office accessories neatly arranged.',
                'description_ar' => 'منظم مكتب مصمم لترتيب الأقلام والقرطاسية والإكسسوارات المكتبية الصغيرة.',
            ],
            [
                'sku' => '068',
                'name_en' => 'Stapler',
                'name_ar' => 'دباسة',
                'unit' => 'piece',
                'product_image' => 'products/068.jpg',
                'description_en' => 'Compact stapler suitable for organizing documents at home, school, or the office.',
                'description_ar' => 'دباسة مدمجة مناسبة لترتيب المستندات في المنزل أو المدرسة أو المكتب.',
            ],
            [
                'sku' => '069',
                'name_en' => 'Calculator',
                'name_ar' => 'آلة حاسبة',
                'unit' => 'piece',
                'product_image' => 'products/069.jpg',
                'description_en' => 'Practical calculator suitable for everyday calculations at school, home, or the office.',
                'description_ar' => 'آلة حاسبة عملية مناسبة للحسابات اليومية في المدرسة أو المنزل أو المكتب.',
            ],
            [
                'sku' => '070',
                'name_en' => 'Printer Paper A4',
                'name_ar' => 'ورق طباعة A4',
                'unit' => 'pack',
                'product_image' => 'products/070.jpg',
                'description_en' => 'A4 printer paper suitable for printing documents, reports, forms, and everyday office materials.',
                'description_ar' => 'ورق طباعة مقاس A4 مناسب لطباعة المستندات والتقارير والنماذج والمواد المكتبية اليومية.',
            ],
            [
                'sku' => '071',
                'name_en' => 'File Folder Set',
                'name_ar' => 'مجموعة ملفات مستندات',
                'unit' => 'set',
                'product_image' => 'products/071.jpg',
                'description_en' => 'File folder set designed to organize and store documents, papers, and office records.',
                'description_ar' => 'مجموعة ملفات مصممة لتنظيم وحفظ المستندات والأوراق والسجلات المكتبية.',
            ],

            [
                'sku' => '072',
                'name_en' => 'Ceramic Coffee Mug',
                'name_ar' => 'كوب قهوة سيراميك',
                'unit' => 'piece',
                'product_image' => 'products/072.jpg',
                'description_en' => 'Ceramic coffee mug suitable for serving coffee, tea, and other hot beverages.',
                'description_ar' => 'كوب قهوة مصنوع من السيراميك مناسب لتقديم القهوة والشاي والمشروبات الساخنة.',
            ],
            [
                'sku' => '073',
                'name_en' => 'Electric Kettle',
                'name_ar' => 'غلاية كهربائية',
                'unit' => 'piece',
                'product_image' => 'products/073.jpg',
                'description_en' => 'Electric kettle designed to heat water quickly for tea, coffee, and other hot beverages.',
                'description_ar' => 'غلاية كهربائية مصممة لتسخين المياه بسرعة لتحضير الشاي والقهوة والمشروبات الساخنة.',
            ],
            [
                'sku' => '074',
                'name_en' => 'Toaster',
                'name_ar' => 'محمصة خبز',
                'unit' => 'piece',
                'product_image' => 'products/074.jpg',
                'description_en' => 'Kitchen toaster designed for convenient preparation of toasted bread and breakfast items.',
                'description_ar' => 'محمصة خبز للمطبخ مصممة لتحضير الخبز المحمص ووجبات الإفطار بسهولة.',
            ],
            [
                'sku' => '075',
                'name_en' => 'Blender',
                'name_ar' => 'خلاط كهربائي',
                'unit' => 'piece',
                'product_image' => 'products/075.jpg',
                'description_en' => 'Kitchen blender suitable for preparing smoothies, sauces, drinks, and blended ingredients.',
                'description_ar' => 'خلاط كهربائي للمطبخ مناسب لتحضير العصائر والصلصات والمشروبات والمكونات المخلوطة.',
            ],
            [
                'sku' => '076',
                'name_en' => 'Nonstick Frying Pan',
                'name_ar' => 'مقلاة غير لاصقة',
                'unit' => 'piece',
                'product_image' => 'products/076.jpg',
                'description_en' => 'Nonstick frying pan suitable for cooking eggs, vegetables, meats, and everyday meals.',
                'description_ar' => 'مقلاة غير لاصقة مناسبة لطهي البيض والخضروات واللحوم والوجبات اليومية.',
            ],
            [
                'sku' => '077',
                'name_en' => 'Chef Knife',
                'name_ar' => 'سكين طاهٍ',
                'unit' => 'piece',
                'product_image' => 'products/077.jpg',
                'description_en' => 'Versatile chef knife designed for chopping, slicing, and preparing a wide variety of ingredients.',
                'description_ar' => 'سكين طاهٍ متعدد الاستخدامات لتقطيع وتحضير مجموعة متنوعة من المكونات.',
            ],
            [
                'sku' => '078',
                'name_en' => 'Cutting Board',
                'name_ar' => 'لوح تقطيع',
                'unit' => 'piece',
                'product_image' => 'products/078.jpg',
                'description_en' => 'Kitchen cutting board providing a convenient surface for preparing vegetables, meat, and other ingredients.',
                'description_ar' => 'لوح تقطيع للمطبخ يوفر سطحاً مناسباً لتحضير الخضروات واللحوم والمكونات المختلفة.',
            ],
            [
                'sku' => '079',
                'name_en' => 'Food Storage Containers',
                'name_ar' => 'حاويات حفظ الطعام',
                'unit' => 'set',
                'product_image' => 'products/079.jpg',
                'description_en' => 'Food storage containers suitable for organizing, storing, and transporting meals and ingredients.',
                'description_ar' => 'حاويات لحفظ الطعام مناسبة لتنظيم وتخزين ونقل الوجبات والمكونات.',
            ],
            [
                'sku' => '080',
                'name_en' => 'Kitchen Scale',
                'name_ar' => 'ميزان مطبخ',
                'unit' => 'piece',
                'product_image' => 'products/080.jpg',
                'description_en' => 'Kitchen scale designed for accurately measuring ingredients during cooking and baking.',
                'description_ar' => 'ميزان مطبخ مصمم لقياس المكونات بدقة أثناء الطبخ والخبز.',
            ],
            [
                'sku' => '081',
                'name_en' => 'Reusable Lunch Box',
                'name_ar' => 'علبة غداء قابلة لإعادة الاستخدام',
                'unit' => 'piece',
                'product_image' => 'products/081.jpg',
                'description_en' => 'Reusable lunch box suitable for carrying meals and snacks to work, school, or outdoor activities.',
                'description_ar' => 'علبة غداء قابلة لإعادة الاستخدام مناسبة لحمل الوجبات والوجبات الخفيفة للعمل أو المدرسة أو الرحلات.',
            ],
            [
                'sku' => '082',
                'name_en' => 'Glass Water Pitcher',
                'name_ar' => 'إبريق مياه زجاجي',
                'unit' => 'piece',
                'product_image' => 'products/082.jpg',
                'description_en' => 'Glass water pitcher suitable for serving water, juice, and other cold beverages.',
                'description_ar' => 'إبريق مياه زجاجي مناسب لتقديم المياه والعصائر والمشروبات الباردة.',
            ],

            [
                'sku' => '083',
                'name_en' => 'Bath Towel',
                'name_ar' => 'منشفة حمام',
                'unit' => 'piece',
                'product_image' => 'products/083.jpg',
                'description_en' => 'Soft bath towel designed for comfortable and effective drying after bathing.',
                'description_ar' => 'منشفة حمام ناعمة مصممة لتجفيف الجسم بشكل مريح وفعال بعد الاستحمام.',
            ],
            [
                'sku' => '084',
                'name_en' => 'Bed Sheet Set',
                'name_ar' => 'طقم أغطية سرير',
                'unit' => 'set',
                'product_image' => 'products/084.jpg',
                'description_en' => 'Bed sheet set suitable for creating a comfortable and tidy sleeping environment.',
                'description_ar' => 'طقم أغطية سرير مناسب لتوفير بيئة نوم مريحة ومرتبة.',
            ],
            [
                'sku' => '085',
                'name_en' => 'Throw Pillow',
                'name_ar' => 'وسادة ديكورية',
                'unit' => 'piece',
                'product_image' => 'products/085.jpg',
                'description_en' => 'Decorative throw pillow suitable for adding comfort and style to sofas, beds, and chairs.',
                'description_ar' => 'وسادة ديكورية مناسبة لإضافة الراحة والأناقة إلى الأرائك والأسرة والكراسي.',
            ],
            [
                'sku' => '086',
                'name_en' => 'Fleece Blanket',
                'name_ar' => 'بطانية فليس',
                'unit' => 'piece',
                'product_image' => 'products/086.jpg',
                'description_en' => 'Soft fleece blanket providing warmth and comfort for bedrooms, sofas, and travel.',
                'description_ar' => 'بطانية فليس ناعمة توفر الدفء والراحة لغرف النوم والأرائك والسفر.',
            ],
            [
                'sku' => '087',
                'name_en' => 'Table Lamp',
                'name_ar' => 'مصباح طاولة',
                'unit' => 'piece',
                'product_image' => 'products/087.jpg',
                'description_en' => 'Table lamp suitable for bedrooms, living rooms, desks, and decorative home lighting.',
                'description_ar' => 'مصباح طاولة مناسب لغرف النوم وغرف المعيشة والمكاتب والإضاءة المنزلية الديكورية.',
            ],
            [
                'sku' => '088',
                'name_en' => 'Wall Clock',
                'name_ar' => 'ساعة حائط',
                'unit' => 'piece',
                'product_image' => 'products/088.jpg',
                'description_en' => 'Wall clock combining practical timekeeping with a simple decorative design for home or office.',
                'description_ar' => 'ساعة حائط تجمع بين عرض الوقت والتصميم الديكوري البسيط للمنزل أو المكتب.',
            ],
            [
                'sku' => '089',
                'name_en' => 'Storage Basket',
                'name_ar' => 'سلة تخزين',
                'unit' => 'piece',
                'product_image' => 'products/089.jpg',
                'description_en' => 'Storage basket suitable for organizing clothes, accessories, toys, and household items.',
                'description_ar' => 'سلة تخزين مناسبة لتنظيم الملابس والإكسسوارات والألعاب والأغراض المنزلية.',
            ],
            [
                'sku' => '090',
                'name_en' => 'Laundry Basket',
                'name_ar' => 'سلة غسيل',
                'unit' => 'piece',
                'product_image' => 'products/090.jpg',
                'description_en' => 'Practical laundry basket designed for collecting and transporting clothes before and after washing.',
                'description_ar' => 'سلة غسيل عملية لجمع ونقل الملابس قبل وبعد الغسيل.',
            ],
            [
                'sku' => '091',
                'name_en' => 'Microfiber Cleaning Cloths',
                'name_ar' => 'أقمشة تنظيف من المايكروفايبر',
                'unit' => 'pack',
                'product_image' => 'products/091.jpg',
                'description_en' => 'Microfiber cleaning cloths suitable for cleaning surfaces, appliances, furniture, and glass.',
                'description_ar' => 'أقمشة تنظيف من المايكروفايبر مناسبة لتنظيف الأسطح والأجهزة والأثاث والزجاج.',
            ],
            [
                'sku' => '092',
                'name_en' => 'Vacuum Cleaner',
                'name_ar' => 'مكنسة كهربائية',
                'unit' => 'piece',
                'product_image' => 'products/092.jpg',
                'description_en' => 'Vacuum cleaner designed to remove dust, dirt, and debris from floors and household surfaces.',
                'description_ar' => 'مكنسة كهربائية مصممة لإزالة الغبار والأوساخ والمخلفات من الأرضيات والأسطح المنزلية.',
            ],
            [
                'sku' => '093',
                'name_en' => 'Air Purifier',
                'name_ar' => 'منقي هواء',
                'unit' => 'piece',
                'product_image' => 'products/093.jpg',
                'description_en' => 'Air purifier designed to help improve indoor air quality by filtering common airborne particles.',
                'description_ar' => 'منقي هواء مصمم للمساعدة في تحسين جودة الهواء الداخلي من خلال ترشيح الجزيئات المحمولة في الهواء.',
            ],
            [
                'sku' => '094',
                'name_en' => 'Humidifier',
                'name_ar' => 'مرطب هواء',
                'unit' => 'piece',
                'product_image' => 'products/094.jpg',
                'description_en' => 'Home humidifier designed to add moisture to indoor air and improve room comfort.',
                'description_ar' => 'مرطب هواء منزلي مصمم لإضافة الرطوبة إلى الهواء الداخلي وتحسين راحة الغرفة.',
            ],
            [
                'sku' => '095',
                'name_en' => 'Extension Cord',
                'name_ar' => 'سلك تمديد كهربائي',
                'unit' => 'piece',
                'product_image' => 'products/095.jpg',
                'description_en' => 'Extension cord providing additional reach for connecting compatible electrical devices.',
                'description_ar' => 'سلك تمديد كهربائي يوفر طولاً إضافياً لتوصيل الأجهزة الكهربائية المتوافقة.',
            ],
            [
                'sku' => '096',
                'name_en' => 'Power Strip',
                'name_ar' => 'مشترك كهربائي',
                'unit' => 'piece',
                'product_image' => 'products/096.jpg',
                'description_en' => 'Power strip designed to provide multiple electrical outlets for compatible household and office devices.',
                'description_ar' => 'مشترك كهربائي يوفر عدة مقابس لتوصيل الأجهزة المنزلية والمكتبية المتوافقة.',
            ],
            [
                'sku' => '097',
                'name_en' => 'Wall Mirror',
                'name_ar' => 'مرآة حائط',
                'unit' => 'piece',
                'product_image' => 'products/097.jpg',
                'description_en' => 'Wall mirror suitable for bedrooms, bathrooms, hallways, and decorative home spaces.',
                'description_ar' => 'مرآة حائط مناسبة لغرف النوم والحمامات والممرات والمساحات المنزلية الديكورية.',
            ],
            [
                'sku' => '098',
                'name_en' => 'Picture Frame',
                'name_ar' => 'إطار صور',
                'unit' => 'piece',
                'product_image' => 'products/098.jpg',
                'description_en' => 'Picture frame designed for displaying photographs, artwork, and memorable moments.',
                'description_ar' => 'إطار صور مصمم لعرض الصور والأعمال الفنية والذكريات المميزة.',
            ],
            [
                'sku' => '099',
                'name_en' => 'Scented Candle',
                'name_ar' => 'شمعة معطرة',
                'unit' => 'piece',
                'product_image' => 'products/099.jpg',
                'description_en' => 'Scented candle suitable for creating a pleasant and relaxing atmosphere at home.',
                'description_ar' => 'شمعة معطرة مناسبة لإضفاء أجواء لطيفة ومريحة في المنزل.',
            ],
            [
                'sku' => '100',
                'name_en' => 'Essential Oil Diffuser',
                'name_ar' => 'ناشر الزيوت العطرية',
                'unit' => 'piece',
                'product_image' => 'products/100.jpg',
                'description_en' => 'Essential oil diffuser designed to disperse fragrance and create a relaxing indoor atmosphere.',
                'description_ar' => 'ناشر للزيوت العطرية مصمم لنشر الروائح وخلق أجواء مريحة داخل المنزل.',
            ],

            [
                'sku' => '101',
                'name_en' => 'Shampoo',
                'name_ar' => 'شامبو',
                'unit' => 'bottle',
                'product_image' => 'products/101.jpg',
                'description_en' => 'Hair shampoo designed for regular cleansing and everyday hair care.',
                'description_ar' => 'شامبو للشعر مصمم للتنظيف المنتظم والعناية اليومية بالشعر.',
            ],
            [
                'sku' => '102',
                'name_en' => 'Moisturizing Face Cream',
                'name_ar' => 'كريم مرطب للوجه',
                'unit' => 'piece',
                'product_image' => 'products/102.jpg',
                'description_en' => 'Moisturizing face cream designed to help keep facial skin soft and hydrated.',
                'description_ar' => 'كريم مرطب للوجه يساعد على الحفاظ على نعومة وترطيب البشرة.',
            ],
            [
                'sku' => '103',
                'name_en' => 'Hand Soap',
                'name_ar' => 'صابون لليدين',
                'unit' => 'bottle',
                'product_image' => 'products/103.jpg',
                'description_en' => 'Hand soap suitable for regular hand washing and everyday personal hygiene.',
                'description_ar' => 'صابون لليدين مناسب لغسل اليدين بشكل منتظم والعناية بالنظافة الشخصية اليومية.',
            ],
            [
                'sku' => '104',
                'name_en' => 'Toothbrush',
                'name_ar' => 'فرشاة أسنان',
                'unit' => 'piece',
                'product_image' => 'products/104.jpg',
                'description_en' => 'Toothbrush designed for daily oral cleaning and maintaining good dental hygiene.',
                'description_ar' => 'فرشاة أسنان مصممة لتنظيف الفم يومياً والحفاظ على نظافة الأسنان.',
            ],
            [
                'sku' => '105',
                'name_en' => 'Toothpaste',
                'name_ar' => 'معجون أسنان',
                'unit' => 'tube',
                'product_image' => 'products/105.jpg',
                'description_en' => 'Everyday toothpaste suitable for regular brushing and maintaining oral cleanliness.',
                'description_ar' => 'معجون أسنان للاستخدام اليومي مناسب لتنظيف الأسنان والحفاظ على نظافة الفم.',
            ],
            [
                'sku' => '106',
                'name_en' => 'Hair Brush',
                'name_ar' => 'فرشاة شعر',
                'unit' => 'piece',
                'product_image' => 'products/106.jpg',
                'description_en' => 'Hair brush suitable for everyday grooming, detangling, and styling.',
                'description_ar' => 'فرشاة شعر مناسبة لتصفيف الشعر وفك التشابك والعناية اليومية.',
            ],
            [
                'sku' => '107',
                'name_en' => 'Electric Hair Trimmer',
                'name_ar' => 'آلة تشذيب شعر كهربائية',
                'unit' => 'piece',
                'product_image' => 'products/107.jpg',
                'description_en' => 'Electric hair trimmer designed for convenient grooming and hair trimming at home.',
                'description_ar' => 'آلة تشذيب شعر كهربائية مصممة للعناية الشخصية وتشذيب الشعر بسهولة في المنزل.',
            ],
            [
                'sku' => '108',
                'name_en' => 'Body Lotion',
                'name_ar' => 'لوشن للجسم',
                'unit' => 'bottle',
                'product_image' => 'products/108.jpg',
                'description_en' => 'Body lotion designed to moisturize and soften the skin as part of a daily care routine.',
                'description_ar' => 'لوشن للجسم مصمم لترطيب وتنعيم البشرة ضمن روتين العناية اليومية.',
            ],
            [
                'sku' => '109',
                'name_en' => 'Deodorant',
                'name_ar' => 'مزيل عرق',
                'unit' => 'piece',
                'product_image' => 'products/109.jpg',
                'description_en' => 'Everyday deodorant designed to provide freshness and help control body odor.',
                'description_ar' => 'مزيل عرق للاستخدام اليومي يوفر الانتعاش ويساعد على التحكم في رائحة الجسم.',
            ],
            [
                'sku' => '110',
                'name_en' => 'Manicure Set',
                'name_ar' => 'طقم عناية بالأظافر',
                'unit' => 'set',
                'product_image' => 'products/110.jpg',
                'description_en' => 'Manicure set containing essential tools for basic nail grooming and personal care.',
                'description_ar' => 'طقم عناية بالأظافر يحتوي على الأدوات الأساسية للعناية بالأظافر والنظافة الشخصية.',
            ],

            [
                'sku' => '111',
                'name_en' => 'Car Phone Holder',
                'name_ar' => 'حامل هاتف للسيارة',
                'unit' => 'piece',
                'product_image' => 'products/111.jpg',
                'description_en' => 'Car phone holder designed to keep a smartphone securely positioned and accessible while driving.',
                'description_ar' => 'حامل هاتف للسيارة يساعد على تثبيت الهاتف بشكل آمن وفي مكان يسهل الوصول إليه أثناء القيادة.',
            ],
            [
                'sku' => '112',
                'name_en' => 'Microfiber Car Towels',
                'name_ar' => 'مناشف سيارات من المايكروفايبر',
                'unit' => 'pack',
                'product_image' => 'products/112.jpg',
                'description_en' => 'Microfiber towels suitable for cleaning and drying vehicle interiors and exterior surfaces.',
                'description_ar' => 'مناشف من المايكروفايبر مناسبة لتنظيف وتجفيف الأسطح الداخلية والخارجية للسيارة.',
            ],
            [
                'sku' => '113',
                'name_en' => 'Tire Pressure Gauge',
                'name_ar' => 'مقياس ضغط الإطارات',
                'unit' => 'piece',
                'product_image' => 'products/113.jpg',
                'description_en' => 'Tire pressure gauge designed to help check vehicle tire pressure accurately.',
                'description_ar' => 'مقياس ضغط إطارات يساعد على فحص ضغط إطارات السيارة بدقة.',
            ],
            [
                'sku' => '114',
                'name_en' => 'Jumper Cables',
                'name_ar' => 'كابلات اشتراك للسيارة',
                'unit' => 'set',
                'product_image' => 'products/114.jpg',
                'description_en' => 'Jumper cable set designed for connecting vehicle batteries during emergency starting situations.',
                'description_ar' => 'مجموعة كابلات اشتراك مصممة لتوصيل بطاريات السيارات عند الحاجة إلى تشغيل السيارة في حالات الطوارئ.',
            ],
            [
                'sku' => '115',
                'name_en' => 'Car Air Freshener',
                'name_ar' => 'معطر هواء للسيارة',
                'unit' => 'piece',
                'product_image' => 'products/115.jpg',
                'description_en' => 'Car air freshener designed to provide a pleasant fragrance inside the vehicle.',
                'description_ar' => 'معطر هواء للسيارة مصمم لإضفاء رائحة منعشة وممتعة داخل المركبة.',
            ],
            [
                'sku' => '116',
                'name_en' => 'Windshield Sun Shade',
                'name_ar' => 'حاجب شمس للزجاج الأمامي',
                'unit' => 'piece',
                'product_image' => 'products/116.jpg',
                'description_en' => 'Windshield sun shade designed to reduce direct sunlight entering the vehicle when parked.',
                'description_ar' => 'حاجب شمس للزجاج الأمامي مصمم لتقليل دخول أشعة الشمس المباشرة إلى السيارة أثناء الوقوف.',
            ],
            [
                'sku' => '117',
                'name_en' => 'Emergency Car Kit',
                'name_ar' => 'عدة طوارئ للسيارة',
                'unit' => 'set',
                'product_image' => 'products/117.jpg',
                'description_en' => 'Emergency car kit containing useful supplies for common roadside situations and basic vehicle emergencies.',
                'description_ar' => 'عدة طوارئ للسيارة تحتوي على مستلزمات مفيدة للتعامل مع الحالات الطارئة والمواقف الشائعة على الطريق.',
            ],
            [
                'sku' => '118',
                'name_en' => 'Car Cleaning Brush',
                'name_ar' => 'فرشاة تنظيف السيارة',
                'unit' => 'piece',
                'product_image' => 'products/118.jpg',
                'description_en' => 'Car cleaning brush suitable for removing dust and dirt from vehicle surfaces and interior areas.',
                'description_ar' => 'فرشاة تنظيف مناسبة لإزالة الغبار والأوساخ من أسطح السيارة والأجزاء الداخلية.',
            ],
            [
                'sku' => '119',
                'name_en' => 'Motorcycle Gloves',
                'name_ar' => 'قفازات دراجات نارية',
                'unit' => 'pair',
                'product_image' => 'products/119.jpg',
                'description_en' => 'Motorcycle gloves designed to provide hand coverage and comfort during motorcycle riding.',
                'description_ar' => 'قفازات للدراجات النارية مصممة لتوفير تغطية وراحة لليدين أثناء القيادة.',
            ],
            [
                'sku' => '120',
                'name_en' => 'USB Car Charger',
                'name_ar' => 'شاحن USB للسيارة',
                'unit' => 'piece',
                'product_image' => 'products/120.jpg',
                'description_en' => 'USB car charger designed to conveniently charge compatible mobile devices while traveling.',
                'description_ar' => 'شاحن USB للسيارة مصمم لشحن الأجهزة المحمولة المتوافقة بسهولة أثناء السفر.',
            ],

            [
                'sku' => '121',
                'name_en' => 'Organic Coffee Beans',
                'name_ar' => 'حبوب قهوة عضوية',
                'unit' => 'pack',
                'product_image' => 'products/121.jpg',
                'description_en' => 'Organic coffee beans suitable for preparing fresh coffee using various brewing methods.',
                'description_ar' => 'حبوب قهوة عضوية مناسبة لتحضير قهوة طازجة باستخدام طرق تحضير مختلفة.',
            ],
            [
                'sku' => '122',
                'name_en' => 'Green Tea',
                'name_ar' => 'شاي أخضر',
                'unit' => 'pack',
                'product_image' => 'products/122.jpg',
                'description_en' => 'Green tea suitable for preparing a refreshing hot beverage for everyday enjoyment.',
                'description_ar' => 'شاي أخضر مناسب لتحضير مشروب ساخن ومنعش للاستمتاع به يومياً.',
            ],
            [
                'sku' => '123',
                'name_en' => 'Peanut Butter',
                'name_ar' => 'زبدة الفول السوداني',
                'unit' => 'jar',
                'product_image' => 'products/123.jpg',
                'description_en' => 'Peanut butter suitable for spreading on bread, adding to snacks, and preparing recipes.',
                'description_ar' => 'زبدة فول سوداني مناسبة للدهن على الخبز وإضافتها إلى الوجبات الخفيفة والوصفات المختلفة.',
            ],
            [
                'sku' => '124',
                'name_en' => 'Strawberry Jam',
                'name_ar' => 'مربى الفراولة',
                'unit' => 'jar',
                'product_image' => 'products/124.jpg',
                'description_en' => 'Strawberry jam suitable for breakfast, sandwiches, desserts, and everyday snacks.',
                'description_ar' => 'مربى الفراولة مناسب للفطور والسندويشات والحلويات والوجبات الخفيفة.',
            ],
            [
                'sku' => '125',
                'name_en' => 'Pasta 500g',
                'name_ar' => 'مكرونة 500 جرام',
                'unit' => 'pack',
                'product_image' => 'products/125.jpg',
                'description_en' => '500g pasta suitable for preparing a variety of quick and delicious meals.',
                'description_ar' => 'مكرونة بوزن 500 جرام مناسبة لتحضير مجموعة متنوعة من الوجبات السريعة واللذيذة.',
            ],
            [
                'sku' => '126',
                'name_en' => 'Basmati Rice 1kg',
                'name_ar' => 'أرز بسمتي 1 كجم',
                'unit' => 'bag',
                'product_image' => 'products/126.jpg',
                'description_en' => '1kg basmati rice suitable for everyday meals, rice dishes, and a variety of recipes.',
                'description_ar' => 'أرز بسمتي بوزن 1 كجم مناسب للوجبات اليومية وأطباق الأرز والوصفات المتنوعة.',
            ],
            [
                'sku' => '127',
                'name_en' => 'Olive Oil 500ml',
                'name_ar' => 'زيت زيتون 500 مل',
                'unit' => 'bottle',
                'product_image' => 'products/127.jpg',
                'description_en' => '500ml olive oil suitable for cooking, salad dressing, and everyday food preparation.',
                'description_ar' => 'زيت زيتون بسعة 500 مل مناسب للطبخ وتتبيل السلطات وتحضير الطعام اليومي.',
            ],
            [
                'sku' => '128',
                'name_en' => 'Honey 350g',
                'name_ar' => 'عسل 350 جرام',
                'unit' => 'jar',
                'product_image' => 'products/128.jpg',
                'description_en' => '350g honey suitable for sweetening drinks, spreading on bread, and preparing desserts.',
                'description_ar' => 'عسل بوزن 350 جرام مناسب لتحلية المشروبات والدهن على الخبز وتحضير الحلويات.',
            ],
            [
                'sku' => '129',
                'name_en' => 'Granola 400g',
                'name_ar' => 'جرانولا 400 جرام',
                'unit' => 'pack',
                'product_image' => 'products/129.jpg',
                'description_en' => '400g granola suitable for breakfast, yogurt, snacks, and quick everyday meals.',
                'description_ar' => 'جرانولا بوزن 400 جرام مناسبة للفطور والزبادي والوجبات الخفيفة والوجبات السريعة.',
            ],
            [
                'sku' => '130',
                'name_en' => 'Dark Chocolate 100g',
                'name_ar' => 'شوكولاتة داكنة 100 جرام',
                'unit' => 'bar',
                'product_image' => 'products/130.jpg',
                'description_en' => '100g dark chocolate bar suitable for enjoying as a snack or using in desserts.',
                'description_ar' => 'لوح شوكولاتة داكنة بوزن 100 جرام مناسب كوجبة خفيفة أو لاستخدامه في الحلويات.',
            ],

            [
                'sku' => '131',
                'name_en' => 'Pet Food 2kg',
                'name_ar' => 'طعام للحيوانات الأليفة 2 كجم',
                'unit' => 'bag',
                'product_image' => 'products/131.jpg',
                'description_en' => '2kg pet food suitable for feeding household pets as part of their regular diet.',
                'description_ar' => 'طعام للحيوانات الأليفة بوزن 2 كجم مناسب للتغذية اليومية للحيوانات المنزلية.',
            ],
            [
                'sku' => '132',
                'name_en' => 'Cat Litter',
                'name_ar' => 'رمل قطط',
                'unit' => 'bag',
                'product_image' => 'products/132.jpg',
                'description_en' => 'Cat litter designed for maintaining a clean and comfortable litter area for cats.',
                'description_ar' => 'رمل قطط مصمم للحفاظ على منطقة نظيفة ومريحة للقطط.',
            ],
            [
                'sku' => '133',
                'name_en' => 'Dog Leash',
                'name_ar' => 'مقود للكلاب',
                'unit' => 'piece',
                'product_image' => 'products/133.jpg',
                'description_en' => 'Dog leash suitable for controlled and comfortable walks with dogs.',
                'description_ar' => 'مقود للكلاب مناسب للمشي مع الكلاب بطريقة مريحة ومنظمة.',
            ],
            [
                'sku' => '134',
                'name_en' => 'Pet Bowl',
                'name_ar' => 'وعاء للحيوانات الأليفة',
                'unit' => 'piece',
                'product_image' => 'products/134.jpg',
                'description_en' => 'Pet bowl suitable for serving food or water to household pets.',
                'description_ar' => 'وعاء للحيوانات الأليفة مناسب لتقديم الطعام أو الماء للحيوانات المنزلية.',
            ],
            [
                'sku' => '135',
                'name_en' => 'Pet Grooming Brush',
                'name_ar' => 'فرشاة عناية بالحيوانات الأليفة',
                'unit' => 'piece',
                'product_image' => 'products/135.jpg',
                'description_en' => 'Pet grooming brush suitable for regular brushing and coat care for household pets.',
                'description_ar' => 'فرشاة للعناية بالحيوانات الأليفة مناسبة لتمشيط الفراء والعناية به بشكل منتظم.',
            ],

            [
                'sku' => '136',
                'name_en' => 'Travel Neck Pillow',
                'name_ar' => 'وسادة رقبة للسفر',
                'unit' => 'piece',
                'product_image' => 'products/136.jpg',
                'description_en' => 'Travel neck pillow designed to provide comfortable neck support during journeys.',
                'description_ar' => 'وسادة رقبة للسفر مصممة لتوفير دعم مريح للرقبة أثناء الرحلات.',
            ],
            [
                'sku' => '137',
                'name_en' => 'Reusable Shopping Bag',
                'name_ar' => 'حقيبة تسوق قابلة لإعادة الاستخدام',
                'unit' => 'piece',
                'product_image' => 'products/137.jpg',
                'description_en' => 'Reusable shopping bag suitable for groceries, retail purchases, and everyday carrying.',
                'description_ar' => 'حقيبة تسوق قابلة لإعادة الاستخدام مناسبة للبقالة والمشتريات والاستخدام اليومي.',
            ],
            [
                'sku' => '138',
                'name_en' => 'Travel Adapter',
                'name_ar' => 'محول سفر',
                'unit' => 'piece',
                'product_image' => 'products/138.jpg',
                'description_en' => 'Travel adapter designed to help connect compatible devices to electrical outlets while traveling.',
                'description_ar' => 'محول سفر يساعد على توصيل الأجهزة المتوافقة بالمقابس الكهربائية أثناء السفر.',
            ],
            [
                'sku' => '139',
                'name_en' => 'Luggage Scale',
                'name_ar' => 'ميزان أمتعة',
                'unit' => 'piece',
                'product_image' => 'products/139.jpg',
                'description_en' => 'Portable luggage scale designed to help check baggage weight before traveling.',
                'description_ar' => 'ميزان أمتعة محمول يساعد على معرفة وزن الحقائب قبل السفر.',
            ],
            [
                'sku' => '140',
                'name_en' => 'Packing Cubes Set',
                'name_ar' => 'مجموعة مكعبات تنظيم الأمتعة',
                'unit' => 'set',
                'product_image' => 'products/140.jpg',
                'description_en' => 'Packing cubes set designed to organize clothing and personal belongings efficiently inside luggage.',
                'description_ar' => 'مجموعة مكعبات لتنظيم الأمتعة تساعد على ترتيب الملابس والأغراض الشخصية داخل حقيبة السفر.',
            ],

            [
                'sku' => '141',
                'name_en' => 'USB-C Hub',
                'name_ar' => 'موزع USB-C',
                'unit' => 'piece',
                'product_image' => 'products/141.jpg',
                'description_en' => 'USB-C hub providing additional connectivity options for compatible laptops and devices.',
                'description_ar' => 'موزع USB-C يوفر خيارات اتصال إضافية لأجهزة الكمبيوتر المحمولة والأجهزة المتوافقة.',
            ],
            [
                'sku' => '142',
                'name_en' => 'Portable SSD 1TB',
                'name_ar' => 'وحدة تخزين SSD محمولة 1 تيرابايت',
                'unit' => 'piece',
                'product_image' => 'products/142.jpg',
                'description_en' => 'Portable 1TB SSD providing convenient storage and fast access to files, photos, videos, and documents.',
                'description_ar' => 'وحدة تخزين SSD محمولة بسعة 1 تيرابايت توفر مساحة تخزين وسرعة وصول مناسبة للملفات والصور والفيديوهات.',
            ],
            [
                'sku' => '143',
                'name_en' => 'Laptop Stand',
                'name_ar' => 'حامل لابتوب',
                'unit' => 'piece',
                'product_image' => 'products/143.jpg',
                'description_en' => 'Laptop stand designed to elevate a laptop for a more comfortable desk setup and viewing position.',
                'description_ar' => 'حامل لابتوب مصمم لرفع الكمبيوتر المحمول وتحسين وضعية المشاهدة والعمل على المكتب.',
            ],
            [
                'sku' => '144',
                'name_en' => 'Desk Mat',
                'name_ar' => 'حصيرة مكتب',
                'unit' => 'piece',
                'product_image' => 'products/144.jpg',
                'description_en' => 'Desk mat providing a smooth protective surface for keyboards, mice, and other desktop accessories.',
                'description_ar' => 'حصيرة مكتب توفر سطحاً ناعماً وحامياً للوحة المفاتيح والفأرة والإكسسوارات المكتبية.',
            ],
            [
                'sku' => '145',
                'name_en' => 'Reusable Food Wrap',
                'name_ar' => 'غلاف طعام قابل لإعادة الاستخدام',
                'unit' => 'pack',
                'product_image' => 'products/145.jpg',
                'description_en' => 'Reusable food wrap suitable for covering and storing food while reducing the need for disposable wrapping materials.',
                'description_ar' => 'غلاف طعام قابل لإعادة الاستخدام لتغطية وحفظ الطعام وتقليل الحاجة إلى مواد التغليف ذات الاستخدام الواحد.',
            ],
            [
                'sku' => '146',
                'name_en' => 'Silicone Baking Mat',
                'name_ar' => 'حصيرة خبز سيليكون',
                'unit' => 'piece',
                'product_image' => 'products/146.jpg',
                'description_en' => 'Silicone baking mat providing a reusable nonstick surface for baking and food preparation.',
                'description_ar' => 'حصيرة خبز من السيليكون توفر سطحاً غير لاصق وقابلاً لإعادة الاستخدام للخبز وتحضير الطعام.',
            ],
            [
                'sku' => '147',
                'name_en' => 'Digital Kitchen Timer',
                'name_ar' => 'مؤقت مطبخ رقمي',
                'unit' => 'piece',
                'product_image' => 'products/147.jpg',
                'description_en' => 'Digital kitchen timer suitable for cooking, baking, meal preparation, and everyday timing tasks.',
                'description_ar' => 'مؤقت مطبخ رقمي مناسب للطبخ والخبز وتحضير الوجبات ومهام ضبط الوقت اليومية.',
            ],
            [
                'sku' => '148',
                'name_en' => 'Shoe Storage Organizer',
                'name_ar' => 'منظم لتخزين الأحذية',
                'unit' => 'piece',
                'product_image' => 'products/148.jpg',
                'description_en' => 'Shoe storage organizer designed to keep footwear neatly arranged and easy to access.',
                'description_ar' => 'منظم لتخزين الأحذية مصمم للحفاظ على الأحذية مرتبة وسهلة الوصول.',
            ],
            [
                'sku' => '149',
                'name_en' => 'Door Mat',
                'name_ar' => 'دعاسة باب',
                'unit' => 'piece',
                'product_image' => 'products/149.jpg',
                'description_en' => 'Door mat suitable for placing at entrances to help keep indoor floors cleaner.',
                'description_ar' => 'دعاسة باب مناسبة للمداخل للمساعدة في الحفاظ على نظافة الأرضيات الداخلية.',
            ],
            [
                'sku' => '150',
                'name_en' => 'Folding Umbrella',
                'name_ar' => 'مظلة قابلة للطي',
                'unit' => 'piece',
                'product_image' => 'products/150.jpg',
                'description_en' => 'Compact folding umbrella designed for convenient protection from rain while traveling or commuting.',
                'description_ar' => 'مظلة مدمجة قابلة للطي مصممة للحماية من المطر أثناء السفر أو التنقل.',
            ],
        ];

        foreach ($products as $product) {
            $product['product_image'] = Storage::url($product['product_image']);

            Product::updateOrCreate(
                ['sku' => $product['sku']],
                $product
            );
        }
         foreach (range(1, 20) as $i) {
            $product = Product::factory()->create();

            $product->categories()->attach(
                Category::inRandomOrder()->limit(fake()->numberBetween(1, 3))->pluck('id')
            );
        }
    }
}